export const QUERY_KEYS = {
  LOGIN: "login",
  ORGANIZATIONS: "organizations",
  ACCOUNTS: "accounts",
  ACCOUNTS_BALANCE_HISTORY: "accounts-balance-history",
  PAYMENTS: "payments",
  ITEMS: "items",
  DATES: "dates",
  RETIREMENT_PLANS: "retirementPlans",
  RETIREMENT_PLAN_CONTRIBUTIONS: "retirementPlanContributions",
  RETIREMENT_PLAN_USERS: "retirementPlanUsers",
  RETIREMENT_PLAN_REPORT: "retirementPlanReport",
  FIXED_INCOME_ASSETS: "fixedIncomeAssets",
  TASK_GROUPS: "taskGroups",
  TASK_SCHEDULES: "taskSchedules",
  TASKS: "tasks",
  RECEIPTS: "receipts",
  TAX_RECORDS: "taxRecords",
  TICKER_PRICES: "tickerPrices",
} as const
