/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as TrendsRouteImport } from './app/trends'
import { Route as TaxesRouteImport } from './app/taxes'
import { Route as TasksRouteImport } from './app/tasks'
import { Route as SetPasswordRouteImport } from './app/setPassword'
import { Route as RetirementRouteImport } from './app/retirement'
import { Route as RegisterRouteImport } from './app/register'
import { Route as ReceiptsRouteImport } from './app/receipts'
import { Route as PaymentsRouteImport } from './app/payments'
import { Route as MealsOutRouteImport } from './app/mealsOut'
import { Route as InvestmentsRouteImport } from './app/investments'
import { Route as ForgotPasswordRouteImport } from './app/forgotPassword'
import { Route as FixedIncomeRouteImport } from './app/fixedIncome'
import { Route as AccountsRouteImport } from './app/accounts'
import { Route as IndexRouteImport } from './app/index'
import { Route as ApiTickerPricesRouteImport } from './app/api/tickerPrices'
import { Route as ApiResetPasswordRouteImport } from './app/api/resetPassword'
import { Route as ApiRegisterRouteImport } from './app/api/register'
import { Route as ApiOrganizationsRouteImport } from './app/api/organizations'
import { Route as ApiLoginRouteImport } from './app/api/login'
import { Route as ApiForgotPasswordRouteImport } from './app/api/forgotPassword'
import { Route as ApiOrganizationsRemoveUserRouteImport } from './app/api/organizations.removeUser'
import { Route as ApiOrganizationsAddUserRouteImport } from './app/api/organizations.addUser'
import { Route as ApiOrganizationsIdRouteImport } from './app/api/organizations.$id'
import { Route as ApiOrganizationsIdTaxRecordsRouteImport } from './app/api/organizations.$id.taxRecords'
import { Route as ApiOrganizationsIdTasksRouteImport } from './app/api/organizations.$id.tasks'
import { Route as ApiOrganizationsIdScrapeEmailRouteImport } from './app/api/organizations.$id.scrapeEmail'
import { Route as ApiOrganizationsIdRetirementPlansRouteImport } from './app/api/organizations.$id.retirementPlans'
import { Route as ApiOrganizationsIdReceiptsRouteImport } from './app/api/organizations.$id.receipts'
import { Route as ApiOrganizationsIdPaymentsRouteImport } from './app/api/organizations.$id.payments'
import { Route as ApiOrganizationsIdMealsOutRouteImport } from './app/api/organizations.$id.mealsOut'
import { Route as ApiOrganizationsIdFixedIncomeAssetsRouteImport } from './app/api/organizations.$id.fixedIncomeAssets'
import { Route as ApiOrganizationsIdExportRouteImport } from './app/api/organizations.$id.export'
import { Route as ApiOrganizationsIdDatesRouteImport } from './app/api/organizations.$id.dates'
import { Route as ApiOrganizationsIdAccountsRouteImport } from './app/api/organizations.$id.accounts'
import { Route as ApiOrganizationsIdUsersUserIdRouteImport } from './app/api/organizations.$id.users.$userId'
import { Route as ApiOrganizationsIdTaxRecordsTaxRecordIdRouteImport } from './app/api/organizations.$id.taxRecords.$taxRecordId'
import { Route as ApiOrganizationsIdTasksStatsRouteImport } from './app/api/organizations.$id.tasks.stats'
import { Route as ApiOrganizationsIdTasksSchedulesRouteImport } from './app/api/organizations.$id.tasks.schedules'
import { Route as ApiOrganizationsIdTasksGroupsRouteImport } from './app/api/organizations.$id.tasks.groups'
import { Route as ApiOrganizationsIdTasksTaskIdRouteImport } from './app/api/organizations.$id.tasks.$taskId'
import { Route as ApiOrganizationsIdRetirementPlansRetirementPlanIdRouteImport } from './app/api/organizations.$id.retirementPlans.$retirementPlanId'
import { Route as ApiOrganizationsIdReceiptsReceiptIdRouteImport } from './app/api/organizations.$id.receipts.$receiptId'
import { Route as ApiOrganizationsIdPlaidLinkTokenRouteImport } from './app/api/organizations.$id.plaid.linkToken'
import { Route as ApiOrganizationsIdPlaidCredentialRouteImport } from './app/api/organizations.$id.plaid.credential'
import { Route as ApiOrganizationsIdPlaidAccountsRouteImport } from './app/api/organizations.$id.plaid.accounts'
import { Route as ApiOrganizationsIdPaymentsPaymentIdRouteImport } from './app/api/organizations.$id.payments.$paymentId'
import { Route as ApiOrganizationsIdMealsOutMealOutIdRouteImport } from './app/api/organizations.$id.mealsOut.$mealOutId'
import { Route as ApiOrganizationsIdItemsItemIdRouteImport } from './app/api/organizations.$id.items.$itemId'
import { Route as ApiOrganizationsIdFixedIncomeAssetsFixedIncomeAssetIdRouteImport } from './app/api/organizations.$id.fixedIncomeAssets.$fixedIncomeAssetId'
import { Route as ApiOrganizationsIdDatesDateRouteImport } from './app/api/organizations.$id.dates.$date'
import { Route as ApiOrganizationsIdAccountsBalanceHistoryRouteImport } from './app/api/organizations.$id.accounts.balanceHistory'
import { Route as ApiOrganizationsIdAccountsAccountIdRouteImport } from './app/api/organizations.$id.accounts.$accountId'
import { Route as ApiOrganizationsIdTaxRecordsTaxRecordIdOpenRouteImport } from './app/api/organizations.$id.taxRecords.$taxRecordId.open'
import { Route as ApiOrganizationsIdTaxRecordsTaxRecordIdDownloadRouteImport } from './app/api/organizations.$id.taxRecords.$taxRecordId.download'
import { Route as ApiOrganizationsIdTasksSchedulesTaskScheduleIdRouteImport } from './app/api/organizations.$id.tasks.schedules.$taskScheduleId'
import { Route as ApiOrganizationsIdTasksGroupsTaskGroupIdRouteImport } from './app/api/organizations.$id.tasks.groups.$taskGroupId'
import { Route as ApiOrganizationsIdRetirementPlansRetirementPlanIdUsersRouteImport } from './app/api/organizations.$id.retirementPlans.$retirementPlanId.users'
import { Route as ApiOrganizationsIdRetirementPlansRetirementPlanIdReportRouteImport } from './app/api/organizations.$id.retirementPlans.$retirementPlanId.report'
import { Route as ApiOrganizationsIdRetirementPlansRetirementPlanIdContributionsRouteImport } from './app/api/organizations.$id.retirementPlans.$retirementPlanId.contributions'
import { Route as ApiOrganizationsIdReceiptsReceiptIdOpenRouteImport } from './app/api/organizations.$id.receipts.$receiptId.open'
import { Route as ApiOrganizationsIdReceiptsReceiptIdDownloadRouteImport } from './app/api/organizations.$id.receipts.$receiptId.download'
import { Route as ApiOrganizationsIdAccountsAccountIdAssetsRouteImport } from './app/api/organizations.$id.accounts.$accountId.assets'
import { Route as ApiOrganizationsIdAccountsAccountIdAssetsAssetIdRouteImport } from './app/api/organizations.$id.accounts.$accountId.assets.$assetId'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxesRoute = TaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/setPassword',
  path: '/setPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const RetirementRoute = RetirementRouteImport.update({
  id: '/retirement',
  path: '/retirement',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsOutRoute = MealsOutRouteImport.update({
  id: '/mealsOut',
  path: '/mealsOut',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgotPassword',
  path: '/forgotPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const FixedIncomeRoute = FixedIncomeRouteImport.update({
  id: '/fixedIncome',
  path: '/fixedIncome',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTickerPricesRoute = ApiTickerPricesRouteImport.update({
  id: '/api/tickerPrices',
  path: '/api/tickerPrices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResetPasswordRoute = ApiResetPasswordRouteImport.update({
  id: '/api/resetPassword',
  path: '/api/resetPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterRoute = ApiRegisterRouteImport.update({
  id: '/api/register',
  path: '/api/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationsRoute = ApiOrganizationsRouteImport.update({
  id: '/api/organizations',
  path: '/api/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForgotPasswordRoute = ApiForgotPasswordRouteImport.update({
  id: '/api/forgotPassword',
  path: '/api/forgotPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationsRemoveUserRoute =
  ApiOrganizationsRemoveUserRouteImport.update({
    id: '/removeUser',
    path: '/removeUser',
    getParentRoute: () => ApiOrganizationsRoute,
  } as any)
const ApiOrganizationsAddUserRoute = ApiOrganizationsAddUserRouteImport.update({
  id: '/addUser',
  path: '/addUser',
  getParentRoute: () => ApiOrganizationsRoute,
} as any)
const ApiOrganizationsIdRoute = ApiOrganizationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiOrganizationsRoute,
} as any)
const ApiOrganizationsIdTaxRecordsRoute =
  ApiOrganizationsIdTaxRecordsRouteImport.update({
    id: '/taxRecords',
    path: '/taxRecords',
    getParentRoute: () => ApiOrganizationsIdRoute,
  } as any)
const ApiOrganizationsIdTasksRoute = ApiOrganizationsIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ApiOrganizationsIdRoute,
} as any)
const ApiOrganizationsIdScrapeEmailRoute =
  ApiOrganizationsIdScrapeEmailRouteImport.update({
    id: '/scrapeEmail',
    path: '/scrapeEmail',
    getParentRoute: () => ApiOrganizationsIdRoute,
  } as any)
const ApiOrganizationsIdRetirementPlansRoute =
  ApiOrganizationsIdRetirementPlansRouteImport.update({
    id: '/retirementPlans',
    path: '/retirementPlans',
    getParentRoute: () => ApiOrganizationsIdRoute,
  } as any)
const ApiOrganizationsIdReceiptsRoute =
  ApiOrganizationsIdReceiptsRouteImport.update({
    id: '/receipts',
    path: '/receipts',
    getParentRoute: () => ApiOrganizationsIdRoute,
  } as any)
const ApiOrganizationsIdPaymentsRoute =
  ApiOrganizationsIdPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => ApiOrganizationsIdRoute,
  } as any)
const ApiOrganizationsIdMealsOutRoute =
  ApiOrganizationsIdMealsOutRouteImport.update({
    id: '/mealsOut',
    path: '/mealsOut',
    getParentRoute: () => ApiOrganizationsIdRoute,
  } as any)
const ApiOrganizationsIdFixedIncomeAssetsRoute =
  ApiOrganizationsIdFixedIncomeAssetsRouteImport.update({
    id: '/fixedIncomeAssets',
    path: '/fixedIncomeAssets',
    getParentRoute: () => ApiOrganizationsIdRoute,
  } as any)
const ApiOrganizationsIdExportRoute =
  ApiOrganizationsIdExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => ApiOrganizationsIdRoute,
  } as any)
const ApiOrganizationsIdDatesRoute = ApiOrganizationsIdDatesRouteImport.update({
  id: '/dates',
  path: '/dates',
  getParentRoute: () => ApiOrganizationsIdRoute,
} as any)
const ApiOrganizationsIdAccountsRoute =
  ApiOrganizationsIdAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => ApiOrganizationsIdRoute,
  } as any)
const ApiOrganizationsIdUsersUserIdRoute =
  ApiOrganizationsIdUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => ApiOrganizationsIdRoute,
  } as any)
const ApiOrganizationsIdTaxRecordsTaxRecordIdRoute =
  ApiOrganizationsIdTaxRecordsTaxRecordIdRouteImport.update({
    id: '/$taxRecordId',
    path: '/$taxRecordId',
    getParentRoute: () => ApiOrganizationsIdTaxRecordsRoute,
  } as any)
const ApiOrganizationsIdTasksStatsRoute =
  ApiOrganizationsIdTasksStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => ApiOrganizationsIdTasksRoute,
  } as any)
const ApiOrganizationsIdTasksSchedulesRoute =
  ApiOrganizationsIdTasksSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => ApiOrganizationsIdTasksRoute,
  } as any)
const ApiOrganizationsIdTasksGroupsRoute =
  ApiOrganizationsIdTasksGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => ApiOrganizationsIdTasksRoute,
  } as any)
const ApiOrganizationsIdTasksTaskIdRoute =
  ApiOrganizationsIdTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => ApiOrganizationsIdTasksRoute,
  } as any)
const ApiOrganizationsIdRetirementPlansRetirementPlanIdRoute =
  ApiOrganizationsIdRetirementPlansRetirementPlanIdRouteImport.update({
    id: '/$retirementPlanId',
    path: '/$retirementPlanId',
    getParentRoute: () => ApiOrganizationsIdRetirementPlansRoute,
  } as any)
const ApiOrganizationsIdReceiptsReceiptIdRoute =
  ApiOrganizationsIdReceiptsReceiptIdRouteImport.update({
    id: '/$receiptId',
    path: '/$receiptId',
    getParentRoute: () => ApiOrganizationsIdReceiptsRoute,
  } as any)
const ApiOrganizationsIdPlaidLinkTokenRoute =
  ApiOrganizationsIdPlaidLinkTokenRouteImport.update({
    id: '/plaid/linkToken',
    path: '/plaid/linkToken',
    getParentRoute: () => ApiOrganizationsIdRoute,
  } as any)
const ApiOrganizationsIdPlaidCredentialRoute =
  ApiOrganizationsIdPlaidCredentialRouteImport.update({
    id: '/plaid/credential',
    path: '/plaid/credential',
    getParentRoute: () => ApiOrganizationsIdRoute,
  } as any)
const ApiOrganizationsIdPlaidAccountsRoute =
  ApiOrganizationsIdPlaidAccountsRouteImport.update({
    id: '/plaid/accounts',
    path: '/plaid/accounts',
    getParentRoute: () => ApiOrganizationsIdRoute,
  } as any)
const ApiOrganizationsIdPaymentsPaymentIdRoute =
  ApiOrganizationsIdPaymentsPaymentIdRouteImport.update({
    id: '/$paymentId',
    path: '/$paymentId',
    getParentRoute: () => ApiOrganizationsIdPaymentsRoute,
  } as any)
const ApiOrganizationsIdMealsOutMealOutIdRoute =
  ApiOrganizationsIdMealsOutMealOutIdRouteImport.update({
    id: '/$mealOutId',
    path: '/$mealOutId',
    getParentRoute: () => ApiOrganizationsIdMealsOutRoute,
  } as any)
const ApiOrganizationsIdItemsItemIdRoute =
  ApiOrganizationsIdItemsItemIdRouteImport.update({
    id: '/items/$itemId',
    path: '/items/$itemId',
    getParentRoute: () => ApiOrganizationsIdRoute,
  } as any)
const ApiOrganizationsIdFixedIncomeAssetsFixedIncomeAssetIdRoute =
  ApiOrganizationsIdFixedIncomeAssetsFixedIncomeAssetIdRouteImport.update({
    id: '/$fixedIncomeAssetId',
    path: '/$fixedIncomeAssetId',
    getParentRoute: () => ApiOrganizationsIdFixedIncomeAssetsRoute,
  } as any)
const ApiOrganizationsIdDatesDateRoute =
  ApiOrganizationsIdDatesDateRouteImport.update({
    id: '/$date',
    path: '/$date',
    getParentRoute: () => ApiOrganizationsIdDatesRoute,
  } as any)
const ApiOrganizationsIdAccountsBalanceHistoryRoute =
  ApiOrganizationsIdAccountsBalanceHistoryRouteImport.update({
    id: '/balanceHistory',
    path: '/balanceHistory',
    getParentRoute: () => ApiOrganizationsIdAccountsRoute,
  } as any)
const ApiOrganizationsIdAccountsAccountIdRoute =
  ApiOrganizationsIdAccountsAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => ApiOrganizationsIdAccountsRoute,
  } as any)
const ApiOrganizationsIdTaxRecordsTaxRecordIdOpenRoute =
  ApiOrganizationsIdTaxRecordsTaxRecordIdOpenRouteImport.update({
    id: '/open',
    path: '/open',
    getParentRoute: () => ApiOrganizationsIdTaxRecordsTaxRecordIdRoute,
  } as any)
const ApiOrganizationsIdTaxRecordsTaxRecordIdDownloadRoute =
  ApiOrganizationsIdTaxRecordsTaxRecordIdDownloadRouteImport.update({
    id: '/download',
    path: '/download',
    getParentRoute: () => ApiOrganizationsIdTaxRecordsTaxRecordIdRoute,
  } as any)
const ApiOrganizationsIdTasksSchedulesTaskScheduleIdRoute =
  ApiOrganizationsIdTasksSchedulesTaskScheduleIdRouteImport.update({
    id: '/$taskScheduleId',
    path: '/$taskScheduleId',
    getParentRoute: () => ApiOrganizationsIdTasksSchedulesRoute,
  } as any)
const ApiOrganizationsIdTasksGroupsTaskGroupIdRoute =
  ApiOrganizationsIdTasksGroupsTaskGroupIdRouteImport.update({
    id: '/$taskGroupId',
    path: '/$taskGroupId',
    getParentRoute: () => ApiOrganizationsIdTasksGroupsRoute,
  } as any)
const ApiOrganizationsIdRetirementPlansRetirementPlanIdUsersRoute =
  ApiOrganizationsIdRetirementPlansRetirementPlanIdUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () =>
      ApiOrganizationsIdRetirementPlansRetirementPlanIdRoute,
  } as any)
const ApiOrganizationsIdRetirementPlansRetirementPlanIdReportRoute =
  ApiOrganizationsIdRetirementPlansRetirementPlanIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () =>
      ApiOrganizationsIdRetirementPlansRetirementPlanIdRoute,
  } as any)
const ApiOrganizationsIdRetirementPlansRetirementPlanIdContributionsRoute =
  ApiOrganizationsIdRetirementPlansRetirementPlanIdContributionsRouteImport.update(
    {
      id: '/contributions',
      path: '/contributions',
      getParentRoute: () =>
        ApiOrganizationsIdRetirementPlansRetirementPlanIdRoute,
    } as any,
  )
const ApiOrganizationsIdReceiptsReceiptIdOpenRoute =
  ApiOrganizationsIdReceiptsReceiptIdOpenRouteImport.update({
    id: '/open',
    path: '/open',
    getParentRoute: () => ApiOrganizationsIdReceiptsReceiptIdRoute,
  } as any)
const ApiOrganizationsIdReceiptsReceiptIdDownloadRoute =
  ApiOrganizationsIdReceiptsReceiptIdDownloadRouteImport.update({
    id: '/download',
    path: '/download',
    getParentRoute: () => ApiOrganizationsIdReceiptsReceiptIdRoute,
  } as any)
const ApiOrganizationsIdAccountsAccountIdAssetsRoute =
  ApiOrganizationsIdAccountsAccountIdAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => ApiOrganizationsIdAccountsAccountIdRoute,
  } as any)
const ApiOrganizationsIdAccountsAccountIdAssetsAssetIdRoute =
  ApiOrganizationsIdAccountsAccountIdAssetsAssetIdRouteImport.update({
    id: '/$assetId',
    path: '/$assetId',
    getParentRoute: () => ApiOrganizationsIdAccountsAccountIdAssetsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/fixedIncome': typeof FixedIncomeRoute
  '/forgotPassword': typeof ForgotPasswordRoute
  '/investments': typeof InvestmentsRoute
  '/mealsOut': typeof MealsOutRoute
  '/payments': typeof PaymentsRoute
  '/receipts': typeof ReceiptsRoute
  '/register': typeof RegisterRoute
  '/retirement': typeof RetirementRoute
  '/setPassword': typeof SetPasswordRoute
  '/tasks': typeof TasksRoute
  '/taxes': typeof TaxesRoute
  '/trends': typeof TrendsRoute
  '/api/forgotPassword': typeof ApiForgotPasswordRoute
  '/api/login': typeof ApiLoginRoute
  '/api/organizations': typeof ApiOrganizationsRouteWithChildren
  '/api/register': typeof ApiRegisterRoute
  '/api/resetPassword': typeof ApiResetPasswordRoute
  '/api/tickerPrices': typeof ApiTickerPricesRoute
  '/api/organizations/$id': typeof ApiOrganizationsIdRouteWithChildren
  '/api/organizations/addUser': typeof ApiOrganizationsAddUserRoute
  '/api/organizations/removeUser': typeof ApiOrganizationsRemoveUserRoute
  '/api/organizations/$id/accounts': typeof ApiOrganizationsIdAccountsRouteWithChildren
  '/api/organizations/$id/dates': typeof ApiOrganizationsIdDatesRouteWithChildren
  '/api/organizations/$id/export': typeof ApiOrganizationsIdExportRoute
  '/api/organizations/$id/fixedIncomeAssets': typeof ApiOrganizationsIdFixedIncomeAssetsRouteWithChildren
  '/api/organizations/$id/mealsOut': typeof ApiOrganizationsIdMealsOutRouteWithChildren
  '/api/organizations/$id/payments': typeof ApiOrganizationsIdPaymentsRouteWithChildren
  '/api/organizations/$id/receipts': typeof ApiOrganizationsIdReceiptsRouteWithChildren
  '/api/organizations/$id/retirementPlans': typeof ApiOrganizationsIdRetirementPlansRouteWithChildren
  '/api/organizations/$id/scrapeEmail': typeof ApiOrganizationsIdScrapeEmailRoute
  '/api/organizations/$id/tasks': typeof ApiOrganizationsIdTasksRouteWithChildren
  '/api/organizations/$id/taxRecords': typeof ApiOrganizationsIdTaxRecordsRouteWithChildren
  '/api/organizations/$id/accounts/$accountId': typeof ApiOrganizationsIdAccountsAccountIdRouteWithChildren
  '/api/organizations/$id/accounts/balanceHistory': typeof ApiOrganizationsIdAccountsBalanceHistoryRoute
  '/api/organizations/$id/dates/$date': typeof ApiOrganizationsIdDatesDateRoute
  '/api/organizations/$id/fixedIncomeAssets/$fixedIncomeAssetId': typeof ApiOrganizationsIdFixedIncomeAssetsFixedIncomeAssetIdRoute
  '/api/organizations/$id/items/$itemId': typeof ApiOrganizationsIdItemsItemIdRoute
  '/api/organizations/$id/mealsOut/$mealOutId': typeof ApiOrganizationsIdMealsOutMealOutIdRoute
  '/api/organizations/$id/payments/$paymentId': typeof ApiOrganizationsIdPaymentsPaymentIdRoute
  '/api/organizations/$id/plaid/accounts': typeof ApiOrganizationsIdPlaidAccountsRoute
  '/api/organizations/$id/plaid/credential': typeof ApiOrganizationsIdPlaidCredentialRoute
  '/api/organizations/$id/plaid/linkToken': typeof ApiOrganizationsIdPlaidLinkTokenRoute
  '/api/organizations/$id/receipts/$receiptId': typeof ApiOrganizationsIdReceiptsReceiptIdRouteWithChildren
  '/api/organizations/$id/retirementPlans/$retirementPlanId': typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdRouteWithChildren
  '/api/organizations/$id/tasks/$taskId': typeof ApiOrganizationsIdTasksTaskIdRoute
  '/api/organizations/$id/tasks/groups': typeof ApiOrganizationsIdTasksGroupsRouteWithChildren
  '/api/organizations/$id/tasks/schedules': typeof ApiOrganizationsIdTasksSchedulesRouteWithChildren
  '/api/organizations/$id/tasks/stats': typeof ApiOrganizationsIdTasksStatsRoute
  '/api/organizations/$id/taxRecords/$taxRecordId': typeof ApiOrganizationsIdTaxRecordsTaxRecordIdRouteWithChildren
  '/api/organizations/$id/users/$userId': typeof ApiOrganizationsIdUsersUserIdRoute
  '/api/organizations/$id/accounts/$accountId/assets': typeof ApiOrganizationsIdAccountsAccountIdAssetsRouteWithChildren
  '/api/organizations/$id/receipts/$receiptId/download': typeof ApiOrganizationsIdReceiptsReceiptIdDownloadRoute
  '/api/organizations/$id/receipts/$receiptId/open': typeof ApiOrganizationsIdReceiptsReceiptIdOpenRoute
  '/api/organizations/$id/retirementPlans/$retirementPlanId/contributions': typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdContributionsRoute
  '/api/organizations/$id/retirementPlans/$retirementPlanId/report': typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdReportRoute
  '/api/organizations/$id/retirementPlans/$retirementPlanId/users': typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdUsersRoute
  '/api/organizations/$id/tasks/groups/$taskGroupId': typeof ApiOrganizationsIdTasksGroupsTaskGroupIdRoute
  '/api/organizations/$id/tasks/schedules/$taskScheduleId': typeof ApiOrganizationsIdTasksSchedulesTaskScheduleIdRoute
  '/api/organizations/$id/taxRecords/$taxRecordId/download': typeof ApiOrganizationsIdTaxRecordsTaxRecordIdDownloadRoute
  '/api/organizations/$id/taxRecords/$taxRecordId/open': typeof ApiOrganizationsIdTaxRecordsTaxRecordIdOpenRoute
  '/api/organizations/$id/accounts/$accountId/assets/$assetId': typeof ApiOrganizationsIdAccountsAccountIdAssetsAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/fixedIncome': typeof FixedIncomeRoute
  '/forgotPassword': typeof ForgotPasswordRoute
  '/investments': typeof InvestmentsRoute
  '/mealsOut': typeof MealsOutRoute
  '/payments': typeof PaymentsRoute
  '/receipts': typeof ReceiptsRoute
  '/register': typeof RegisterRoute
  '/retirement': typeof RetirementRoute
  '/setPassword': typeof SetPasswordRoute
  '/tasks': typeof TasksRoute
  '/taxes': typeof TaxesRoute
  '/trends': typeof TrendsRoute
  '/api/forgotPassword': typeof ApiForgotPasswordRoute
  '/api/login': typeof ApiLoginRoute
  '/api/organizations': typeof ApiOrganizationsRouteWithChildren
  '/api/register': typeof ApiRegisterRoute
  '/api/resetPassword': typeof ApiResetPasswordRoute
  '/api/tickerPrices': typeof ApiTickerPricesRoute
  '/api/organizations/$id': typeof ApiOrganizationsIdRouteWithChildren
  '/api/organizations/addUser': typeof ApiOrganizationsAddUserRoute
  '/api/organizations/removeUser': typeof ApiOrganizationsRemoveUserRoute
  '/api/organizations/$id/accounts': typeof ApiOrganizationsIdAccountsRouteWithChildren
  '/api/organizations/$id/dates': typeof ApiOrganizationsIdDatesRouteWithChildren
  '/api/organizations/$id/export': typeof ApiOrganizationsIdExportRoute
  '/api/organizations/$id/fixedIncomeAssets': typeof ApiOrganizationsIdFixedIncomeAssetsRouteWithChildren
  '/api/organizations/$id/mealsOut': typeof ApiOrganizationsIdMealsOutRouteWithChildren
  '/api/organizations/$id/payments': typeof ApiOrganizationsIdPaymentsRouteWithChildren
  '/api/organizations/$id/receipts': typeof ApiOrganizationsIdReceiptsRouteWithChildren
  '/api/organizations/$id/retirementPlans': typeof ApiOrganizationsIdRetirementPlansRouteWithChildren
  '/api/organizations/$id/scrapeEmail': typeof ApiOrganizationsIdScrapeEmailRoute
  '/api/organizations/$id/tasks': typeof ApiOrganizationsIdTasksRouteWithChildren
  '/api/organizations/$id/taxRecords': typeof ApiOrganizationsIdTaxRecordsRouteWithChildren
  '/api/organizations/$id/accounts/$accountId': typeof ApiOrganizationsIdAccountsAccountIdRouteWithChildren
  '/api/organizations/$id/accounts/balanceHistory': typeof ApiOrganizationsIdAccountsBalanceHistoryRoute
  '/api/organizations/$id/dates/$date': typeof ApiOrganizationsIdDatesDateRoute
  '/api/organizations/$id/fixedIncomeAssets/$fixedIncomeAssetId': typeof ApiOrganizationsIdFixedIncomeAssetsFixedIncomeAssetIdRoute
  '/api/organizations/$id/items/$itemId': typeof ApiOrganizationsIdItemsItemIdRoute
  '/api/organizations/$id/mealsOut/$mealOutId': typeof ApiOrganizationsIdMealsOutMealOutIdRoute
  '/api/organizations/$id/payments/$paymentId': typeof ApiOrganizationsIdPaymentsPaymentIdRoute
  '/api/organizations/$id/plaid/accounts': typeof ApiOrganizationsIdPlaidAccountsRoute
  '/api/organizations/$id/plaid/credential': typeof ApiOrganizationsIdPlaidCredentialRoute
  '/api/organizations/$id/plaid/linkToken': typeof ApiOrganizationsIdPlaidLinkTokenRoute
  '/api/organizations/$id/receipts/$receiptId': typeof ApiOrganizationsIdReceiptsReceiptIdRouteWithChildren
  '/api/organizations/$id/retirementPlans/$retirementPlanId': typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdRouteWithChildren
  '/api/organizations/$id/tasks/$taskId': typeof ApiOrganizationsIdTasksTaskIdRoute
  '/api/organizations/$id/tasks/groups': typeof ApiOrganizationsIdTasksGroupsRouteWithChildren
  '/api/organizations/$id/tasks/schedules': typeof ApiOrganizationsIdTasksSchedulesRouteWithChildren
  '/api/organizations/$id/tasks/stats': typeof ApiOrganizationsIdTasksStatsRoute
  '/api/organizations/$id/taxRecords/$taxRecordId': typeof ApiOrganizationsIdTaxRecordsTaxRecordIdRouteWithChildren
  '/api/organizations/$id/users/$userId': typeof ApiOrganizationsIdUsersUserIdRoute
  '/api/organizations/$id/accounts/$accountId/assets': typeof ApiOrganizationsIdAccountsAccountIdAssetsRouteWithChildren
  '/api/organizations/$id/receipts/$receiptId/download': typeof ApiOrganizationsIdReceiptsReceiptIdDownloadRoute
  '/api/organizations/$id/receipts/$receiptId/open': typeof ApiOrganizationsIdReceiptsReceiptIdOpenRoute
  '/api/organizations/$id/retirementPlans/$retirementPlanId/contributions': typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdContributionsRoute
  '/api/organizations/$id/retirementPlans/$retirementPlanId/report': typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdReportRoute
  '/api/organizations/$id/retirementPlans/$retirementPlanId/users': typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdUsersRoute
  '/api/organizations/$id/tasks/groups/$taskGroupId': typeof ApiOrganizationsIdTasksGroupsTaskGroupIdRoute
  '/api/organizations/$id/tasks/schedules/$taskScheduleId': typeof ApiOrganizationsIdTasksSchedulesTaskScheduleIdRoute
  '/api/organizations/$id/taxRecords/$taxRecordId/download': typeof ApiOrganizationsIdTaxRecordsTaxRecordIdDownloadRoute
  '/api/organizations/$id/taxRecords/$taxRecordId/open': typeof ApiOrganizationsIdTaxRecordsTaxRecordIdOpenRoute
  '/api/organizations/$id/accounts/$accountId/assets/$assetId': typeof ApiOrganizationsIdAccountsAccountIdAssetsAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/fixedIncome': typeof FixedIncomeRoute
  '/forgotPassword': typeof ForgotPasswordRoute
  '/investments': typeof InvestmentsRoute
  '/mealsOut': typeof MealsOutRoute
  '/payments': typeof PaymentsRoute
  '/receipts': typeof ReceiptsRoute
  '/register': typeof RegisterRoute
  '/retirement': typeof RetirementRoute
  '/setPassword': typeof SetPasswordRoute
  '/tasks': typeof TasksRoute
  '/taxes': typeof TaxesRoute
  '/trends': typeof TrendsRoute
  '/api/forgotPassword': typeof ApiForgotPasswordRoute
  '/api/login': typeof ApiLoginRoute
  '/api/organizations': typeof ApiOrganizationsRouteWithChildren
  '/api/register': typeof ApiRegisterRoute
  '/api/resetPassword': typeof ApiResetPasswordRoute
  '/api/tickerPrices': typeof ApiTickerPricesRoute
  '/api/organizations/$id': typeof ApiOrganizationsIdRouteWithChildren
  '/api/organizations/addUser': typeof ApiOrganizationsAddUserRoute
  '/api/organizations/removeUser': typeof ApiOrganizationsRemoveUserRoute
  '/api/organizations/$id/accounts': typeof ApiOrganizationsIdAccountsRouteWithChildren
  '/api/organizations/$id/dates': typeof ApiOrganizationsIdDatesRouteWithChildren
  '/api/organizations/$id/export': typeof ApiOrganizationsIdExportRoute
  '/api/organizations/$id/fixedIncomeAssets': typeof ApiOrganizationsIdFixedIncomeAssetsRouteWithChildren
  '/api/organizations/$id/mealsOut': typeof ApiOrganizationsIdMealsOutRouteWithChildren
  '/api/organizations/$id/payments': typeof ApiOrganizationsIdPaymentsRouteWithChildren
  '/api/organizations/$id/receipts': typeof ApiOrganizationsIdReceiptsRouteWithChildren
  '/api/organizations/$id/retirementPlans': typeof ApiOrganizationsIdRetirementPlansRouteWithChildren
  '/api/organizations/$id/scrapeEmail': typeof ApiOrganizationsIdScrapeEmailRoute
  '/api/organizations/$id/tasks': typeof ApiOrganizationsIdTasksRouteWithChildren
  '/api/organizations/$id/taxRecords': typeof ApiOrganizationsIdTaxRecordsRouteWithChildren
  '/api/organizations/$id/accounts/$accountId': typeof ApiOrganizationsIdAccountsAccountIdRouteWithChildren
  '/api/organizations/$id/accounts/balanceHistory': typeof ApiOrganizationsIdAccountsBalanceHistoryRoute
  '/api/organizations/$id/dates/$date': typeof ApiOrganizationsIdDatesDateRoute
  '/api/organizations/$id/fixedIncomeAssets/$fixedIncomeAssetId': typeof ApiOrganizationsIdFixedIncomeAssetsFixedIncomeAssetIdRoute
  '/api/organizations/$id/items/$itemId': typeof ApiOrganizationsIdItemsItemIdRoute
  '/api/organizations/$id/mealsOut/$mealOutId': typeof ApiOrganizationsIdMealsOutMealOutIdRoute
  '/api/organizations/$id/payments/$paymentId': typeof ApiOrganizationsIdPaymentsPaymentIdRoute
  '/api/organizations/$id/plaid/accounts': typeof ApiOrganizationsIdPlaidAccountsRoute
  '/api/organizations/$id/plaid/credential': typeof ApiOrganizationsIdPlaidCredentialRoute
  '/api/organizations/$id/plaid/linkToken': typeof ApiOrganizationsIdPlaidLinkTokenRoute
  '/api/organizations/$id/receipts/$receiptId': typeof ApiOrganizationsIdReceiptsReceiptIdRouteWithChildren
  '/api/organizations/$id/retirementPlans/$retirementPlanId': typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdRouteWithChildren
  '/api/organizations/$id/tasks/$taskId': typeof ApiOrganizationsIdTasksTaskIdRoute
  '/api/organizations/$id/tasks/groups': typeof ApiOrganizationsIdTasksGroupsRouteWithChildren
  '/api/organizations/$id/tasks/schedules': typeof ApiOrganizationsIdTasksSchedulesRouteWithChildren
  '/api/organizations/$id/tasks/stats': typeof ApiOrganizationsIdTasksStatsRoute
  '/api/organizations/$id/taxRecords/$taxRecordId': typeof ApiOrganizationsIdTaxRecordsTaxRecordIdRouteWithChildren
  '/api/organizations/$id/users/$userId': typeof ApiOrganizationsIdUsersUserIdRoute
  '/api/organizations/$id/accounts/$accountId/assets': typeof ApiOrganizationsIdAccountsAccountIdAssetsRouteWithChildren
  '/api/organizations/$id/receipts/$receiptId/download': typeof ApiOrganizationsIdReceiptsReceiptIdDownloadRoute
  '/api/organizations/$id/receipts/$receiptId/open': typeof ApiOrganizationsIdReceiptsReceiptIdOpenRoute
  '/api/organizations/$id/retirementPlans/$retirementPlanId/contributions': typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdContributionsRoute
  '/api/organizations/$id/retirementPlans/$retirementPlanId/report': typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdReportRoute
  '/api/organizations/$id/retirementPlans/$retirementPlanId/users': typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdUsersRoute
  '/api/organizations/$id/tasks/groups/$taskGroupId': typeof ApiOrganizationsIdTasksGroupsTaskGroupIdRoute
  '/api/organizations/$id/tasks/schedules/$taskScheduleId': typeof ApiOrganizationsIdTasksSchedulesTaskScheduleIdRoute
  '/api/organizations/$id/taxRecords/$taxRecordId/download': typeof ApiOrganizationsIdTaxRecordsTaxRecordIdDownloadRoute
  '/api/organizations/$id/taxRecords/$taxRecordId/open': typeof ApiOrganizationsIdTaxRecordsTaxRecordIdOpenRoute
  '/api/organizations/$id/accounts/$accountId/assets/$assetId': typeof ApiOrganizationsIdAccountsAccountIdAssetsAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/fixedIncome'
    | '/forgotPassword'
    | '/investments'
    | '/mealsOut'
    | '/payments'
    | '/receipts'
    | '/register'
    | '/retirement'
    | '/setPassword'
    | '/tasks'
    | '/taxes'
    | '/trends'
    | '/api/forgotPassword'
    | '/api/login'
    | '/api/organizations'
    | '/api/register'
    | '/api/resetPassword'
    | '/api/tickerPrices'
    | '/api/organizations/$id'
    | '/api/organizations/addUser'
    | '/api/organizations/removeUser'
    | '/api/organizations/$id/accounts'
    | '/api/organizations/$id/dates'
    | '/api/organizations/$id/export'
    | '/api/organizations/$id/fixedIncomeAssets'
    | '/api/organizations/$id/mealsOut'
    | '/api/organizations/$id/payments'
    | '/api/organizations/$id/receipts'
    | '/api/organizations/$id/retirementPlans'
    | '/api/organizations/$id/scrapeEmail'
    | '/api/organizations/$id/tasks'
    | '/api/organizations/$id/taxRecords'
    | '/api/organizations/$id/accounts/$accountId'
    | '/api/organizations/$id/accounts/balanceHistory'
    | '/api/organizations/$id/dates/$date'
    | '/api/organizations/$id/fixedIncomeAssets/$fixedIncomeAssetId'
    | '/api/organizations/$id/items/$itemId'
    | '/api/organizations/$id/mealsOut/$mealOutId'
    | '/api/organizations/$id/payments/$paymentId'
    | '/api/organizations/$id/plaid/accounts'
    | '/api/organizations/$id/plaid/credential'
    | '/api/organizations/$id/plaid/linkToken'
    | '/api/organizations/$id/receipts/$receiptId'
    | '/api/organizations/$id/retirementPlans/$retirementPlanId'
    | '/api/organizations/$id/tasks/$taskId'
    | '/api/organizations/$id/tasks/groups'
    | '/api/organizations/$id/tasks/schedules'
    | '/api/organizations/$id/tasks/stats'
    | '/api/organizations/$id/taxRecords/$taxRecordId'
    | '/api/organizations/$id/users/$userId'
    | '/api/organizations/$id/accounts/$accountId/assets'
    | '/api/organizations/$id/receipts/$receiptId/download'
    | '/api/organizations/$id/receipts/$receiptId/open'
    | '/api/organizations/$id/retirementPlans/$retirementPlanId/contributions'
    | '/api/organizations/$id/retirementPlans/$retirementPlanId/report'
    | '/api/organizations/$id/retirementPlans/$retirementPlanId/users'
    | '/api/organizations/$id/tasks/groups/$taskGroupId'
    | '/api/organizations/$id/tasks/schedules/$taskScheduleId'
    | '/api/organizations/$id/taxRecords/$taxRecordId/download'
    | '/api/organizations/$id/taxRecords/$taxRecordId/open'
    | '/api/organizations/$id/accounts/$accountId/assets/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/fixedIncome'
    | '/forgotPassword'
    | '/investments'
    | '/mealsOut'
    | '/payments'
    | '/receipts'
    | '/register'
    | '/retirement'
    | '/setPassword'
    | '/tasks'
    | '/taxes'
    | '/trends'
    | '/api/forgotPassword'
    | '/api/login'
    | '/api/organizations'
    | '/api/register'
    | '/api/resetPassword'
    | '/api/tickerPrices'
    | '/api/organizations/$id'
    | '/api/organizations/addUser'
    | '/api/organizations/removeUser'
    | '/api/organizations/$id/accounts'
    | '/api/organizations/$id/dates'
    | '/api/organizations/$id/export'
    | '/api/organizations/$id/fixedIncomeAssets'
    | '/api/organizations/$id/mealsOut'
    | '/api/organizations/$id/payments'
    | '/api/organizations/$id/receipts'
    | '/api/organizations/$id/retirementPlans'
    | '/api/organizations/$id/scrapeEmail'
    | '/api/organizations/$id/tasks'
    | '/api/organizations/$id/taxRecords'
    | '/api/organizations/$id/accounts/$accountId'
    | '/api/organizations/$id/accounts/balanceHistory'
    | '/api/organizations/$id/dates/$date'
    | '/api/organizations/$id/fixedIncomeAssets/$fixedIncomeAssetId'
    | '/api/organizations/$id/items/$itemId'
    | '/api/organizations/$id/mealsOut/$mealOutId'
    | '/api/organizations/$id/payments/$paymentId'
    | '/api/organizations/$id/plaid/accounts'
    | '/api/organizations/$id/plaid/credential'
    | '/api/organizations/$id/plaid/linkToken'
    | '/api/organizations/$id/receipts/$receiptId'
    | '/api/organizations/$id/retirementPlans/$retirementPlanId'
    | '/api/organizations/$id/tasks/$taskId'
    | '/api/organizations/$id/tasks/groups'
    | '/api/organizations/$id/tasks/schedules'
    | '/api/organizations/$id/tasks/stats'
    | '/api/organizations/$id/taxRecords/$taxRecordId'
    | '/api/organizations/$id/users/$userId'
    | '/api/organizations/$id/accounts/$accountId/assets'
    | '/api/organizations/$id/receipts/$receiptId/download'
    | '/api/organizations/$id/receipts/$receiptId/open'
    | '/api/organizations/$id/retirementPlans/$retirementPlanId/contributions'
    | '/api/organizations/$id/retirementPlans/$retirementPlanId/report'
    | '/api/organizations/$id/retirementPlans/$retirementPlanId/users'
    | '/api/organizations/$id/tasks/groups/$taskGroupId'
    | '/api/organizations/$id/tasks/schedules/$taskScheduleId'
    | '/api/organizations/$id/taxRecords/$taxRecordId/download'
    | '/api/organizations/$id/taxRecords/$taxRecordId/open'
    | '/api/organizations/$id/accounts/$accountId/assets/$assetId'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/fixedIncome'
    | '/forgotPassword'
    | '/investments'
    | '/mealsOut'
    | '/payments'
    | '/receipts'
    | '/register'
    | '/retirement'
    | '/setPassword'
    | '/tasks'
    | '/taxes'
    | '/trends'
    | '/api/forgotPassword'
    | '/api/login'
    | '/api/organizations'
    | '/api/register'
    | '/api/resetPassword'
    | '/api/tickerPrices'
    | '/api/organizations/$id'
    | '/api/organizations/addUser'
    | '/api/organizations/removeUser'
    | '/api/organizations/$id/accounts'
    | '/api/organizations/$id/dates'
    | '/api/organizations/$id/export'
    | '/api/organizations/$id/fixedIncomeAssets'
    | '/api/organizations/$id/mealsOut'
    | '/api/organizations/$id/payments'
    | '/api/organizations/$id/receipts'
    | '/api/organizations/$id/retirementPlans'
    | '/api/organizations/$id/scrapeEmail'
    | '/api/organizations/$id/tasks'
    | '/api/organizations/$id/taxRecords'
    | '/api/organizations/$id/accounts/$accountId'
    | '/api/organizations/$id/accounts/balanceHistory'
    | '/api/organizations/$id/dates/$date'
    | '/api/organizations/$id/fixedIncomeAssets/$fixedIncomeAssetId'
    | '/api/organizations/$id/items/$itemId'
    | '/api/organizations/$id/mealsOut/$mealOutId'
    | '/api/organizations/$id/payments/$paymentId'
    | '/api/organizations/$id/plaid/accounts'
    | '/api/organizations/$id/plaid/credential'
    | '/api/organizations/$id/plaid/linkToken'
    | '/api/organizations/$id/receipts/$receiptId'
    | '/api/organizations/$id/retirementPlans/$retirementPlanId'
    | '/api/organizations/$id/tasks/$taskId'
    | '/api/organizations/$id/tasks/groups'
    | '/api/organizations/$id/tasks/schedules'
    | '/api/organizations/$id/tasks/stats'
    | '/api/organizations/$id/taxRecords/$taxRecordId'
    | '/api/organizations/$id/users/$userId'
    | '/api/organizations/$id/accounts/$accountId/assets'
    | '/api/organizations/$id/receipts/$receiptId/download'
    | '/api/organizations/$id/receipts/$receiptId/open'
    | '/api/organizations/$id/retirementPlans/$retirementPlanId/contributions'
    | '/api/organizations/$id/retirementPlans/$retirementPlanId/report'
    | '/api/organizations/$id/retirementPlans/$retirementPlanId/users'
    | '/api/organizations/$id/tasks/groups/$taskGroupId'
    | '/api/organizations/$id/tasks/schedules/$taskScheduleId'
    | '/api/organizations/$id/taxRecords/$taxRecordId/download'
    | '/api/organizations/$id/taxRecords/$taxRecordId/open'
    | '/api/organizations/$id/accounts/$accountId/assets/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  FixedIncomeRoute: typeof FixedIncomeRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InvestmentsRoute: typeof InvestmentsRoute
  MealsOutRoute: typeof MealsOutRoute
  PaymentsRoute: typeof PaymentsRoute
  ReceiptsRoute: typeof ReceiptsRoute
  RegisterRoute: typeof RegisterRoute
  RetirementRoute: typeof RetirementRoute
  SetPasswordRoute: typeof SetPasswordRoute
  TasksRoute: typeof TasksRoute
  TaxesRoute: typeof TaxesRoute
  TrendsRoute: typeof TrendsRoute
  ApiForgotPasswordRoute: typeof ApiForgotPasswordRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiOrganizationsRoute: typeof ApiOrganizationsRouteWithChildren
  ApiRegisterRoute: typeof ApiRegisterRoute
  ApiResetPasswordRoute: typeof ApiResetPasswordRoute
  ApiTickerPricesRoute: typeof ApiTickerPricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxes': {
      id: '/taxes'
      path: '/taxes'
      fullPath: '/taxes'
      preLoaderRoute: typeof TaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setPassword': {
      id: '/setPassword'
      path: '/setPassword'
      fullPath: '/setPassword'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retirement': {
      id: '/retirement'
      path: '/retirement'
      fullPath: '/retirement'
      preLoaderRoute: typeof RetirementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mealsOut': {
      id: '/mealsOut'
      path: '/mealsOut'
      fullPath: '/mealsOut'
      preLoaderRoute: typeof MealsOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotPassword': {
      id: '/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixedIncome': {
      id: '/fixedIncome'
      path: '/fixedIncome'
      fullPath: '/fixedIncome'
      preLoaderRoute: typeof FixedIncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tickerPrices': {
      id: '/api/tickerPrices'
      path: '/api/tickerPrices'
      fullPath: '/api/tickerPrices'
      preLoaderRoute: typeof ApiTickerPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resetPassword': {
      id: '/api/resetPassword'
      path: '/api/resetPassword'
      fullPath: '/api/resetPassword'
      preLoaderRoute: typeof ApiResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register': {
      id: '/api/register'
      path: '/api/register'
      fullPath: '/api/register'
      preLoaderRoute: typeof ApiRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations': {
      id: '/api/organizations'
      path: '/api/organizations'
      fullPath: '/api/organizations'
      preLoaderRoute: typeof ApiOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forgotPassword': {
      id: '/api/forgotPassword'
      path: '/api/forgotPassword'
      fullPath: '/api/forgotPassword'
      preLoaderRoute: typeof ApiForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations/removeUser': {
      id: '/api/organizations/removeUser'
      path: '/removeUser'
      fullPath: '/api/organizations/removeUser'
      preLoaderRoute: typeof ApiOrganizationsRemoveUserRouteImport
      parentRoute: typeof ApiOrganizationsRoute
    }
    '/api/organizations/addUser': {
      id: '/api/organizations/addUser'
      path: '/addUser'
      fullPath: '/api/organizations/addUser'
      preLoaderRoute: typeof ApiOrganizationsAddUserRouteImport
      parentRoute: typeof ApiOrganizationsRoute
    }
    '/api/organizations/$id': {
      id: '/api/organizations/$id'
      path: '/$id'
      fullPath: '/api/organizations/$id'
      preLoaderRoute: typeof ApiOrganizationsIdRouteImport
      parentRoute: typeof ApiOrganizationsRoute
    }
    '/api/organizations/$id/taxRecords': {
      id: '/api/organizations/$id/taxRecords'
      path: '/taxRecords'
      fullPath: '/api/organizations/$id/taxRecords'
      preLoaderRoute: typeof ApiOrganizationsIdTaxRecordsRouteImport
      parentRoute: typeof ApiOrganizationsIdRoute
    }
    '/api/organizations/$id/tasks': {
      id: '/api/organizations/$id/tasks'
      path: '/tasks'
      fullPath: '/api/organizations/$id/tasks'
      preLoaderRoute: typeof ApiOrganizationsIdTasksRouteImport
      parentRoute: typeof ApiOrganizationsIdRoute
    }
    '/api/organizations/$id/scrapeEmail': {
      id: '/api/organizations/$id/scrapeEmail'
      path: '/scrapeEmail'
      fullPath: '/api/organizations/$id/scrapeEmail'
      preLoaderRoute: typeof ApiOrganizationsIdScrapeEmailRouteImport
      parentRoute: typeof ApiOrganizationsIdRoute
    }
    '/api/organizations/$id/retirementPlans': {
      id: '/api/organizations/$id/retirementPlans'
      path: '/retirementPlans'
      fullPath: '/api/organizations/$id/retirementPlans'
      preLoaderRoute: typeof ApiOrganizationsIdRetirementPlansRouteImport
      parentRoute: typeof ApiOrganizationsIdRoute
    }
    '/api/organizations/$id/receipts': {
      id: '/api/organizations/$id/receipts'
      path: '/receipts'
      fullPath: '/api/organizations/$id/receipts'
      preLoaderRoute: typeof ApiOrganizationsIdReceiptsRouteImport
      parentRoute: typeof ApiOrganizationsIdRoute
    }
    '/api/organizations/$id/payments': {
      id: '/api/organizations/$id/payments'
      path: '/payments'
      fullPath: '/api/organizations/$id/payments'
      preLoaderRoute: typeof ApiOrganizationsIdPaymentsRouteImport
      parentRoute: typeof ApiOrganizationsIdRoute
    }
    '/api/organizations/$id/mealsOut': {
      id: '/api/organizations/$id/mealsOut'
      path: '/mealsOut'
      fullPath: '/api/organizations/$id/mealsOut'
      preLoaderRoute: typeof ApiOrganizationsIdMealsOutRouteImport
      parentRoute: typeof ApiOrganizationsIdRoute
    }
    '/api/organizations/$id/fixedIncomeAssets': {
      id: '/api/organizations/$id/fixedIncomeAssets'
      path: '/fixedIncomeAssets'
      fullPath: '/api/organizations/$id/fixedIncomeAssets'
      preLoaderRoute: typeof ApiOrganizationsIdFixedIncomeAssetsRouteImport
      parentRoute: typeof ApiOrganizationsIdRoute
    }
    '/api/organizations/$id/export': {
      id: '/api/organizations/$id/export'
      path: '/export'
      fullPath: '/api/organizations/$id/export'
      preLoaderRoute: typeof ApiOrganizationsIdExportRouteImport
      parentRoute: typeof ApiOrganizationsIdRoute
    }
    '/api/organizations/$id/dates': {
      id: '/api/organizations/$id/dates'
      path: '/dates'
      fullPath: '/api/organizations/$id/dates'
      preLoaderRoute: typeof ApiOrganizationsIdDatesRouteImport
      parentRoute: typeof ApiOrganizationsIdRoute
    }
    '/api/organizations/$id/accounts': {
      id: '/api/organizations/$id/accounts'
      path: '/accounts'
      fullPath: '/api/organizations/$id/accounts'
      preLoaderRoute: typeof ApiOrganizationsIdAccountsRouteImport
      parentRoute: typeof ApiOrganizationsIdRoute
    }
    '/api/organizations/$id/users/$userId': {
      id: '/api/organizations/$id/users/$userId'
      path: '/users/$userId'
      fullPath: '/api/organizations/$id/users/$userId'
      preLoaderRoute: typeof ApiOrganizationsIdUsersUserIdRouteImport
      parentRoute: typeof ApiOrganizationsIdRoute
    }
    '/api/organizations/$id/taxRecords/$taxRecordId': {
      id: '/api/organizations/$id/taxRecords/$taxRecordId'
      path: '/$taxRecordId'
      fullPath: '/api/organizations/$id/taxRecords/$taxRecordId'
      preLoaderRoute: typeof ApiOrganizationsIdTaxRecordsTaxRecordIdRouteImport
      parentRoute: typeof ApiOrganizationsIdTaxRecordsRoute
    }
    '/api/organizations/$id/tasks/stats': {
      id: '/api/organizations/$id/tasks/stats'
      path: '/stats'
      fullPath: '/api/organizations/$id/tasks/stats'
      preLoaderRoute: typeof ApiOrganizationsIdTasksStatsRouteImport
      parentRoute: typeof ApiOrganizationsIdTasksRoute
    }
    '/api/organizations/$id/tasks/schedules': {
      id: '/api/organizations/$id/tasks/schedules'
      path: '/schedules'
      fullPath: '/api/organizations/$id/tasks/schedules'
      preLoaderRoute: typeof ApiOrganizationsIdTasksSchedulesRouteImport
      parentRoute: typeof ApiOrganizationsIdTasksRoute
    }
    '/api/organizations/$id/tasks/groups': {
      id: '/api/organizations/$id/tasks/groups'
      path: '/groups'
      fullPath: '/api/organizations/$id/tasks/groups'
      preLoaderRoute: typeof ApiOrganizationsIdTasksGroupsRouteImport
      parentRoute: typeof ApiOrganizationsIdTasksRoute
    }
    '/api/organizations/$id/tasks/$taskId': {
      id: '/api/organizations/$id/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/api/organizations/$id/tasks/$taskId'
      preLoaderRoute: typeof ApiOrganizationsIdTasksTaskIdRouteImport
      parentRoute: typeof ApiOrganizationsIdTasksRoute
    }
    '/api/organizations/$id/retirementPlans/$retirementPlanId': {
      id: '/api/organizations/$id/retirementPlans/$retirementPlanId'
      path: '/$retirementPlanId'
      fullPath: '/api/organizations/$id/retirementPlans/$retirementPlanId'
      preLoaderRoute: typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdRouteImport
      parentRoute: typeof ApiOrganizationsIdRetirementPlansRoute
    }
    '/api/organizations/$id/receipts/$receiptId': {
      id: '/api/organizations/$id/receipts/$receiptId'
      path: '/$receiptId'
      fullPath: '/api/organizations/$id/receipts/$receiptId'
      preLoaderRoute: typeof ApiOrganizationsIdReceiptsReceiptIdRouteImport
      parentRoute: typeof ApiOrganizationsIdReceiptsRoute
    }
    '/api/organizations/$id/plaid/linkToken': {
      id: '/api/organizations/$id/plaid/linkToken'
      path: '/plaid/linkToken'
      fullPath: '/api/organizations/$id/plaid/linkToken'
      preLoaderRoute: typeof ApiOrganizationsIdPlaidLinkTokenRouteImport
      parentRoute: typeof ApiOrganizationsIdRoute
    }
    '/api/organizations/$id/plaid/credential': {
      id: '/api/organizations/$id/plaid/credential'
      path: '/plaid/credential'
      fullPath: '/api/organizations/$id/plaid/credential'
      preLoaderRoute: typeof ApiOrganizationsIdPlaidCredentialRouteImport
      parentRoute: typeof ApiOrganizationsIdRoute
    }
    '/api/organizations/$id/plaid/accounts': {
      id: '/api/organizations/$id/plaid/accounts'
      path: '/plaid/accounts'
      fullPath: '/api/organizations/$id/plaid/accounts'
      preLoaderRoute: typeof ApiOrganizationsIdPlaidAccountsRouteImport
      parentRoute: typeof ApiOrganizationsIdRoute
    }
    '/api/organizations/$id/payments/$paymentId': {
      id: '/api/organizations/$id/payments/$paymentId'
      path: '/$paymentId'
      fullPath: '/api/organizations/$id/payments/$paymentId'
      preLoaderRoute: typeof ApiOrganizationsIdPaymentsPaymentIdRouteImport
      parentRoute: typeof ApiOrganizationsIdPaymentsRoute
    }
    '/api/organizations/$id/mealsOut/$mealOutId': {
      id: '/api/organizations/$id/mealsOut/$mealOutId'
      path: '/$mealOutId'
      fullPath: '/api/organizations/$id/mealsOut/$mealOutId'
      preLoaderRoute: typeof ApiOrganizationsIdMealsOutMealOutIdRouteImport
      parentRoute: typeof ApiOrganizationsIdMealsOutRoute
    }
    '/api/organizations/$id/items/$itemId': {
      id: '/api/organizations/$id/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/api/organizations/$id/items/$itemId'
      preLoaderRoute: typeof ApiOrganizationsIdItemsItemIdRouteImport
      parentRoute: typeof ApiOrganizationsIdRoute
    }
    '/api/organizations/$id/fixedIncomeAssets/$fixedIncomeAssetId': {
      id: '/api/organizations/$id/fixedIncomeAssets/$fixedIncomeAssetId'
      path: '/$fixedIncomeAssetId'
      fullPath: '/api/organizations/$id/fixedIncomeAssets/$fixedIncomeAssetId'
      preLoaderRoute: typeof ApiOrganizationsIdFixedIncomeAssetsFixedIncomeAssetIdRouteImport
      parentRoute: typeof ApiOrganizationsIdFixedIncomeAssetsRoute
    }
    '/api/organizations/$id/dates/$date': {
      id: '/api/organizations/$id/dates/$date'
      path: '/$date'
      fullPath: '/api/organizations/$id/dates/$date'
      preLoaderRoute: typeof ApiOrganizationsIdDatesDateRouteImport
      parentRoute: typeof ApiOrganizationsIdDatesRoute
    }
    '/api/organizations/$id/accounts/balanceHistory': {
      id: '/api/organizations/$id/accounts/balanceHistory'
      path: '/balanceHistory'
      fullPath: '/api/organizations/$id/accounts/balanceHistory'
      preLoaderRoute: typeof ApiOrganizationsIdAccountsBalanceHistoryRouteImport
      parentRoute: typeof ApiOrganizationsIdAccountsRoute
    }
    '/api/organizations/$id/accounts/$accountId': {
      id: '/api/organizations/$id/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/api/organizations/$id/accounts/$accountId'
      preLoaderRoute: typeof ApiOrganizationsIdAccountsAccountIdRouteImport
      parentRoute: typeof ApiOrganizationsIdAccountsRoute
    }
    '/api/organizations/$id/taxRecords/$taxRecordId/open': {
      id: '/api/organizations/$id/taxRecords/$taxRecordId/open'
      path: '/open'
      fullPath: '/api/organizations/$id/taxRecords/$taxRecordId/open'
      preLoaderRoute: typeof ApiOrganizationsIdTaxRecordsTaxRecordIdOpenRouteImport
      parentRoute: typeof ApiOrganizationsIdTaxRecordsTaxRecordIdRoute
    }
    '/api/organizations/$id/taxRecords/$taxRecordId/download': {
      id: '/api/organizations/$id/taxRecords/$taxRecordId/download'
      path: '/download'
      fullPath: '/api/organizations/$id/taxRecords/$taxRecordId/download'
      preLoaderRoute: typeof ApiOrganizationsIdTaxRecordsTaxRecordIdDownloadRouteImport
      parentRoute: typeof ApiOrganizationsIdTaxRecordsTaxRecordIdRoute
    }
    '/api/organizations/$id/tasks/schedules/$taskScheduleId': {
      id: '/api/organizations/$id/tasks/schedules/$taskScheduleId'
      path: '/$taskScheduleId'
      fullPath: '/api/organizations/$id/tasks/schedules/$taskScheduleId'
      preLoaderRoute: typeof ApiOrganizationsIdTasksSchedulesTaskScheduleIdRouteImport
      parentRoute: typeof ApiOrganizationsIdTasksSchedulesRoute
    }
    '/api/organizations/$id/tasks/groups/$taskGroupId': {
      id: '/api/organizations/$id/tasks/groups/$taskGroupId'
      path: '/$taskGroupId'
      fullPath: '/api/organizations/$id/tasks/groups/$taskGroupId'
      preLoaderRoute: typeof ApiOrganizationsIdTasksGroupsTaskGroupIdRouteImport
      parentRoute: typeof ApiOrganizationsIdTasksGroupsRoute
    }
    '/api/organizations/$id/retirementPlans/$retirementPlanId/users': {
      id: '/api/organizations/$id/retirementPlans/$retirementPlanId/users'
      path: '/users'
      fullPath: '/api/organizations/$id/retirementPlans/$retirementPlanId/users'
      preLoaderRoute: typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdUsersRouteImport
      parentRoute: typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdRoute
    }
    '/api/organizations/$id/retirementPlans/$retirementPlanId/report': {
      id: '/api/organizations/$id/retirementPlans/$retirementPlanId/report'
      path: '/report'
      fullPath: '/api/organizations/$id/retirementPlans/$retirementPlanId/report'
      preLoaderRoute: typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdReportRouteImport
      parentRoute: typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdRoute
    }
    '/api/organizations/$id/retirementPlans/$retirementPlanId/contributions': {
      id: '/api/organizations/$id/retirementPlans/$retirementPlanId/contributions'
      path: '/contributions'
      fullPath: '/api/organizations/$id/retirementPlans/$retirementPlanId/contributions'
      preLoaderRoute: typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdContributionsRouteImport
      parentRoute: typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdRoute
    }
    '/api/organizations/$id/receipts/$receiptId/open': {
      id: '/api/organizations/$id/receipts/$receiptId/open'
      path: '/open'
      fullPath: '/api/organizations/$id/receipts/$receiptId/open'
      preLoaderRoute: typeof ApiOrganizationsIdReceiptsReceiptIdOpenRouteImport
      parentRoute: typeof ApiOrganizationsIdReceiptsReceiptIdRoute
    }
    '/api/organizations/$id/receipts/$receiptId/download': {
      id: '/api/organizations/$id/receipts/$receiptId/download'
      path: '/download'
      fullPath: '/api/organizations/$id/receipts/$receiptId/download'
      preLoaderRoute: typeof ApiOrganizationsIdReceiptsReceiptIdDownloadRouteImport
      parentRoute: typeof ApiOrganizationsIdReceiptsReceiptIdRoute
    }
    '/api/organizations/$id/accounts/$accountId/assets': {
      id: '/api/organizations/$id/accounts/$accountId/assets'
      path: '/assets'
      fullPath: '/api/organizations/$id/accounts/$accountId/assets'
      preLoaderRoute: typeof ApiOrganizationsIdAccountsAccountIdAssetsRouteImport
      parentRoute: typeof ApiOrganizationsIdAccountsAccountIdRoute
    }
    '/api/organizations/$id/accounts/$accountId/assets/$assetId': {
      id: '/api/organizations/$id/accounts/$accountId/assets/$assetId'
      path: '/$assetId'
      fullPath: '/api/organizations/$id/accounts/$accountId/assets/$assetId'
      preLoaderRoute: typeof ApiOrganizationsIdAccountsAccountIdAssetsAssetIdRouteImport
      parentRoute: typeof ApiOrganizationsIdAccountsAccountIdAssetsRoute
    }
  }
}

interface ApiOrganizationsIdAccountsAccountIdAssetsRouteChildren {
  ApiOrganizationsIdAccountsAccountIdAssetsAssetIdRoute: typeof ApiOrganizationsIdAccountsAccountIdAssetsAssetIdRoute
}

const ApiOrganizationsIdAccountsAccountIdAssetsRouteChildren: ApiOrganizationsIdAccountsAccountIdAssetsRouteChildren =
  {
    ApiOrganizationsIdAccountsAccountIdAssetsAssetIdRoute:
      ApiOrganizationsIdAccountsAccountIdAssetsAssetIdRoute,
  }

const ApiOrganizationsIdAccountsAccountIdAssetsRouteWithChildren =
  ApiOrganizationsIdAccountsAccountIdAssetsRoute._addFileChildren(
    ApiOrganizationsIdAccountsAccountIdAssetsRouteChildren,
  )

interface ApiOrganizationsIdAccountsAccountIdRouteChildren {
  ApiOrganizationsIdAccountsAccountIdAssetsRoute: typeof ApiOrganizationsIdAccountsAccountIdAssetsRouteWithChildren
}

const ApiOrganizationsIdAccountsAccountIdRouteChildren: ApiOrganizationsIdAccountsAccountIdRouteChildren =
  {
    ApiOrganizationsIdAccountsAccountIdAssetsRoute:
      ApiOrganizationsIdAccountsAccountIdAssetsRouteWithChildren,
  }

const ApiOrganizationsIdAccountsAccountIdRouteWithChildren =
  ApiOrganizationsIdAccountsAccountIdRoute._addFileChildren(
    ApiOrganizationsIdAccountsAccountIdRouteChildren,
  )

interface ApiOrganizationsIdAccountsRouteChildren {
  ApiOrganizationsIdAccountsAccountIdRoute: typeof ApiOrganizationsIdAccountsAccountIdRouteWithChildren
  ApiOrganizationsIdAccountsBalanceHistoryRoute: typeof ApiOrganizationsIdAccountsBalanceHistoryRoute
}

const ApiOrganizationsIdAccountsRouteChildren: ApiOrganizationsIdAccountsRouteChildren =
  {
    ApiOrganizationsIdAccountsAccountIdRoute:
      ApiOrganizationsIdAccountsAccountIdRouteWithChildren,
    ApiOrganizationsIdAccountsBalanceHistoryRoute:
      ApiOrganizationsIdAccountsBalanceHistoryRoute,
  }

const ApiOrganizationsIdAccountsRouteWithChildren =
  ApiOrganizationsIdAccountsRoute._addFileChildren(
    ApiOrganizationsIdAccountsRouteChildren,
  )

interface ApiOrganizationsIdDatesRouteChildren {
  ApiOrganizationsIdDatesDateRoute: typeof ApiOrganizationsIdDatesDateRoute
}

const ApiOrganizationsIdDatesRouteChildren: ApiOrganizationsIdDatesRouteChildren =
  {
    ApiOrganizationsIdDatesDateRoute: ApiOrganizationsIdDatesDateRoute,
  }

const ApiOrganizationsIdDatesRouteWithChildren =
  ApiOrganizationsIdDatesRoute._addFileChildren(
    ApiOrganizationsIdDatesRouteChildren,
  )

interface ApiOrganizationsIdFixedIncomeAssetsRouteChildren {
  ApiOrganizationsIdFixedIncomeAssetsFixedIncomeAssetIdRoute: typeof ApiOrganizationsIdFixedIncomeAssetsFixedIncomeAssetIdRoute
}

const ApiOrganizationsIdFixedIncomeAssetsRouteChildren: ApiOrganizationsIdFixedIncomeAssetsRouteChildren =
  {
    ApiOrganizationsIdFixedIncomeAssetsFixedIncomeAssetIdRoute:
      ApiOrganizationsIdFixedIncomeAssetsFixedIncomeAssetIdRoute,
  }

const ApiOrganizationsIdFixedIncomeAssetsRouteWithChildren =
  ApiOrganizationsIdFixedIncomeAssetsRoute._addFileChildren(
    ApiOrganizationsIdFixedIncomeAssetsRouteChildren,
  )

interface ApiOrganizationsIdMealsOutRouteChildren {
  ApiOrganizationsIdMealsOutMealOutIdRoute: typeof ApiOrganizationsIdMealsOutMealOutIdRoute
}

const ApiOrganizationsIdMealsOutRouteChildren: ApiOrganizationsIdMealsOutRouteChildren =
  {
    ApiOrganizationsIdMealsOutMealOutIdRoute:
      ApiOrganizationsIdMealsOutMealOutIdRoute,
  }

const ApiOrganizationsIdMealsOutRouteWithChildren =
  ApiOrganizationsIdMealsOutRoute._addFileChildren(
    ApiOrganizationsIdMealsOutRouteChildren,
  )

interface ApiOrganizationsIdPaymentsRouteChildren {
  ApiOrganizationsIdPaymentsPaymentIdRoute: typeof ApiOrganizationsIdPaymentsPaymentIdRoute
}

const ApiOrganizationsIdPaymentsRouteChildren: ApiOrganizationsIdPaymentsRouteChildren =
  {
    ApiOrganizationsIdPaymentsPaymentIdRoute:
      ApiOrganizationsIdPaymentsPaymentIdRoute,
  }

const ApiOrganizationsIdPaymentsRouteWithChildren =
  ApiOrganizationsIdPaymentsRoute._addFileChildren(
    ApiOrganizationsIdPaymentsRouteChildren,
  )

interface ApiOrganizationsIdReceiptsReceiptIdRouteChildren {
  ApiOrganizationsIdReceiptsReceiptIdDownloadRoute: typeof ApiOrganizationsIdReceiptsReceiptIdDownloadRoute
  ApiOrganizationsIdReceiptsReceiptIdOpenRoute: typeof ApiOrganizationsIdReceiptsReceiptIdOpenRoute
}

const ApiOrganizationsIdReceiptsReceiptIdRouteChildren: ApiOrganizationsIdReceiptsReceiptIdRouteChildren =
  {
    ApiOrganizationsIdReceiptsReceiptIdDownloadRoute:
      ApiOrganizationsIdReceiptsReceiptIdDownloadRoute,
    ApiOrganizationsIdReceiptsReceiptIdOpenRoute:
      ApiOrganizationsIdReceiptsReceiptIdOpenRoute,
  }

const ApiOrganizationsIdReceiptsReceiptIdRouteWithChildren =
  ApiOrganizationsIdReceiptsReceiptIdRoute._addFileChildren(
    ApiOrganizationsIdReceiptsReceiptIdRouteChildren,
  )

interface ApiOrganizationsIdReceiptsRouteChildren {
  ApiOrganizationsIdReceiptsReceiptIdRoute: typeof ApiOrganizationsIdReceiptsReceiptIdRouteWithChildren
}

const ApiOrganizationsIdReceiptsRouteChildren: ApiOrganizationsIdReceiptsRouteChildren =
  {
    ApiOrganizationsIdReceiptsReceiptIdRoute:
      ApiOrganizationsIdReceiptsReceiptIdRouteWithChildren,
  }

const ApiOrganizationsIdReceiptsRouteWithChildren =
  ApiOrganizationsIdReceiptsRoute._addFileChildren(
    ApiOrganizationsIdReceiptsRouteChildren,
  )

interface ApiOrganizationsIdRetirementPlansRetirementPlanIdRouteChildren {
  ApiOrganizationsIdRetirementPlansRetirementPlanIdContributionsRoute: typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdContributionsRoute
  ApiOrganizationsIdRetirementPlansRetirementPlanIdReportRoute: typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdReportRoute
  ApiOrganizationsIdRetirementPlansRetirementPlanIdUsersRoute: typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdUsersRoute
}

const ApiOrganizationsIdRetirementPlansRetirementPlanIdRouteChildren: ApiOrganizationsIdRetirementPlansRetirementPlanIdRouteChildren =
  {
    ApiOrganizationsIdRetirementPlansRetirementPlanIdContributionsRoute:
      ApiOrganizationsIdRetirementPlansRetirementPlanIdContributionsRoute,
    ApiOrganizationsIdRetirementPlansRetirementPlanIdReportRoute:
      ApiOrganizationsIdRetirementPlansRetirementPlanIdReportRoute,
    ApiOrganizationsIdRetirementPlansRetirementPlanIdUsersRoute:
      ApiOrganizationsIdRetirementPlansRetirementPlanIdUsersRoute,
  }

const ApiOrganizationsIdRetirementPlansRetirementPlanIdRouteWithChildren =
  ApiOrganizationsIdRetirementPlansRetirementPlanIdRoute._addFileChildren(
    ApiOrganizationsIdRetirementPlansRetirementPlanIdRouteChildren,
  )

interface ApiOrganizationsIdRetirementPlansRouteChildren {
  ApiOrganizationsIdRetirementPlansRetirementPlanIdRoute: typeof ApiOrganizationsIdRetirementPlansRetirementPlanIdRouteWithChildren
}

const ApiOrganizationsIdRetirementPlansRouteChildren: ApiOrganizationsIdRetirementPlansRouteChildren =
  {
    ApiOrganizationsIdRetirementPlansRetirementPlanIdRoute:
      ApiOrganizationsIdRetirementPlansRetirementPlanIdRouteWithChildren,
  }

const ApiOrganizationsIdRetirementPlansRouteWithChildren =
  ApiOrganizationsIdRetirementPlansRoute._addFileChildren(
    ApiOrganizationsIdRetirementPlansRouteChildren,
  )

interface ApiOrganizationsIdTasksGroupsRouteChildren {
  ApiOrganizationsIdTasksGroupsTaskGroupIdRoute: typeof ApiOrganizationsIdTasksGroupsTaskGroupIdRoute
}

const ApiOrganizationsIdTasksGroupsRouteChildren: ApiOrganizationsIdTasksGroupsRouteChildren =
  {
    ApiOrganizationsIdTasksGroupsTaskGroupIdRoute:
      ApiOrganizationsIdTasksGroupsTaskGroupIdRoute,
  }

const ApiOrganizationsIdTasksGroupsRouteWithChildren =
  ApiOrganizationsIdTasksGroupsRoute._addFileChildren(
    ApiOrganizationsIdTasksGroupsRouteChildren,
  )

interface ApiOrganizationsIdTasksSchedulesRouteChildren {
  ApiOrganizationsIdTasksSchedulesTaskScheduleIdRoute: typeof ApiOrganizationsIdTasksSchedulesTaskScheduleIdRoute
}

const ApiOrganizationsIdTasksSchedulesRouteChildren: ApiOrganizationsIdTasksSchedulesRouteChildren =
  {
    ApiOrganizationsIdTasksSchedulesTaskScheduleIdRoute:
      ApiOrganizationsIdTasksSchedulesTaskScheduleIdRoute,
  }

const ApiOrganizationsIdTasksSchedulesRouteWithChildren =
  ApiOrganizationsIdTasksSchedulesRoute._addFileChildren(
    ApiOrganizationsIdTasksSchedulesRouteChildren,
  )

interface ApiOrganizationsIdTasksRouteChildren {
  ApiOrganizationsIdTasksTaskIdRoute: typeof ApiOrganizationsIdTasksTaskIdRoute
  ApiOrganizationsIdTasksGroupsRoute: typeof ApiOrganizationsIdTasksGroupsRouteWithChildren
  ApiOrganizationsIdTasksSchedulesRoute: typeof ApiOrganizationsIdTasksSchedulesRouteWithChildren
  ApiOrganizationsIdTasksStatsRoute: typeof ApiOrganizationsIdTasksStatsRoute
}

const ApiOrganizationsIdTasksRouteChildren: ApiOrganizationsIdTasksRouteChildren =
  {
    ApiOrganizationsIdTasksTaskIdRoute: ApiOrganizationsIdTasksTaskIdRoute,
    ApiOrganizationsIdTasksGroupsRoute:
      ApiOrganizationsIdTasksGroupsRouteWithChildren,
    ApiOrganizationsIdTasksSchedulesRoute:
      ApiOrganizationsIdTasksSchedulesRouteWithChildren,
    ApiOrganizationsIdTasksStatsRoute: ApiOrganizationsIdTasksStatsRoute,
  }

const ApiOrganizationsIdTasksRouteWithChildren =
  ApiOrganizationsIdTasksRoute._addFileChildren(
    ApiOrganizationsIdTasksRouteChildren,
  )

interface ApiOrganizationsIdTaxRecordsTaxRecordIdRouteChildren {
  ApiOrganizationsIdTaxRecordsTaxRecordIdDownloadRoute: typeof ApiOrganizationsIdTaxRecordsTaxRecordIdDownloadRoute
  ApiOrganizationsIdTaxRecordsTaxRecordIdOpenRoute: typeof ApiOrganizationsIdTaxRecordsTaxRecordIdOpenRoute
}

const ApiOrganizationsIdTaxRecordsTaxRecordIdRouteChildren: ApiOrganizationsIdTaxRecordsTaxRecordIdRouteChildren =
  {
    ApiOrganizationsIdTaxRecordsTaxRecordIdDownloadRoute:
      ApiOrganizationsIdTaxRecordsTaxRecordIdDownloadRoute,
    ApiOrganizationsIdTaxRecordsTaxRecordIdOpenRoute:
      ApiOrganizationsIdTaxRecordsTaxRecordIdOpenRoute,
  }

const ApiOrganizationsIdTaxRecordsTaxRecordIdRouteWithChildren =
  ApiOrganizationsIdTaxRecordsTaxRecordIdRoute._addFileChildren(
    ApiOrganizationsIdTaxRecordsTaxRecordIdRouteChildren,
  )

interface ApiOrganizationsIdTaxRecordsRouteChildren {
  ApiOrganizationsIdTaxRecordsTaxRecordIdRoute: typeof ApiOrganizationsIdTaxRecordsTaxRecordIdRouteWithChildren
}

const ApiOrganizationsIdTaxRecordsRouteChildren: ApiOrganizationsIdTaxRecordsRouteChildren =
  {
    ApiOrganizationsIdTaxRecordsTaxRecordIdRoute:
      ApiOrganizationsIdTaxRecordsTaxRecordIdRouteWithChildren,
  }

const ApiOrganizationsIdTaxRecordsRouteWithChildren =
  ApiOrganizationsIdTaxRecordsRoute._addFileChildren(
    ApiOrganizationsIdTaxRecordsRouteChildren,
  )

interface ApiOrganizationsIdRouteChildren {
  ApiOrganizationsIdAccountsRoute: typeof ApiOrganizationsIdAccountsRouteWithChildren
  ApiOrganizationsIdDatesRoute: typeof ApiOrganizationsIdDatesRouteWithChildren
  ApiOrganizationsIdExportRoute: typeof ApiOrganizationsIdExportRoute
  ApiOrganizationsIdFixedIncomeAssetsRoute: typeof ApiOrganizationsIdFixedIncomeAssetsRouteWithChildren
  ApiOrganizationsIdMealsOutRoute: typeof ApiOrganizationsIdMealsOutRouteWithChildren
  ApiOrganizationsIdPaymentsRoute: typeof ApiOrganizationsIdPaymentsRouteWithChildren
  ApiOrganizationsIdReceiptsRoute: typeof ApiOrganizationsIdReceiptsRouteWithChildren
  ApiOrganizationsIdRetirementPlansRoute: typeof ApiOrganizationsIdRetirementPlansRouteWithChildren
  ApiOrganizationsIdScrapeEmailRoute: typeof ApiOrganizationsIdScrapeEmailRoute
  ApiOrganizationsIdTasksRoute: typeof ApiOrganizationsIdTasksRouteWithChildren
  ApiOrganizationsIdTaxRecordsRoute: typeof ApiOrganizationsIdTaxRecordsRouteWithChildren
  ApiOrganizationsIdItemsItemIdRoute: typeof ApiOrganizationsIdItemsItemIdRoute
  ApiOrganizationsIdPlaidAccountsRoute: typeof ApiOrganizationsIdPlaidAccountsRoute
  ApiOrganizationsIdPlaidCredentialRoute: typeof ApiOrganizationsIdPlaidCredentialRoute
  ApiOrganizationsIdPlaidLinkTokenRoute: typeof ApiOrganizationsIdPlaidLinkTokenRoute
  ApiOrganizationsIdUsersUserIdRoute: typeof ApiOrganizationsIdUsersUserIdRoute
}

const ApiOrganizationsIdRouteChildren: ApiOrganizationsIdRouteChildren = {
  ApiOrganizationsIdAccountsRoute: ApiOrganizationsIdAccountsRouteWithChildren,
  ApiOrganizationsIdDatesRoute: ApiOrganizationsIdDatesRouteWithChildren,
  ApiOrganizationsIdExportRoute: ApiOrganizationsIdExportRoute,
  ApiOrganizationsIdFixedIncomeAssetsRoute:
    ApiOrganizationsIdFixedIncomeAssetsRouteWithChildren,
  ApiOrganizationsIdMealsOutRoute: ApiOrganizationsIdMealsOutRouteWithChildren,
  ApiOrganizationsIdPaymentsRoute: ApiOrganizationsIdPaymentsRouteWithChildren,
  ApiOrganizationsIdReceiptsRoute: ApiOrganizationsIdReceiptsRouteWithChildren,
  ApiOrganizationsIdRetirementPlansRoute:
    ApiOrganizationsIdRetirementPlansRouteWithChildren,
  ApiOrganizationsIdScrapeEmailRoute: ApiOrganizationsIdScrapeEmailRoute,
  ApiOrganizationsIdTasksRoute: ApiOrganizationsIdTasksRouteWithChildren,
  ApiOrganizationsIdTaxRecordsRoute:
    ApiOrganizationsIdTaxRecordsRouteWithChildren,
  ApiOrganizationsIdItemsItemIdRoute: ApiOrganizationsIdItemsItemIdRoute,
  ApiOrganizationsIdPlaidAccountsRoute: ApiOrganizationsIdPlaidAccountsRoute,
  ApiOrganizationsIdPlaidCredentialRoute:
    ApiOrganizationsIdPlaidCredentialRoute,
  ApiOrganizationsIdPlaidLinkTokenRoute: ApiOrganizationsIdPlaidLinkTokenRoute,
  ApiOrganizationsIdUsersUserIdRoute: ApiOrganizationsIdUsersUserIdRoute,
}

const ApiOrganizationsIdRouteWithChildren =
  ApiOrganizationsIdRoute._addFileChildren(ApiOrganizationsIdRouteChildren)

interface ApiOrganizationsRouteChildren {
  ApiOrganizationsIdRoute: typeof ApiOrganizationsIdRouteWithChildren
  ApiOrganizationsAddUserRoute: typeof ApiOrganizationsAddUserRoute
  ApiOrganizationsRemoveUserRoute: typeof ApiOrganizationsRemoveUserRoute
}

const ApiOrganizationsRouteChildren: ApiOrganizationsRouteChildren = {
  ApiOrganizationsIdRoute: ApiOrganizationsIdRouteWithChildren,
  ApiOrganizationsAddUserRoute: ApiOrganizationsAddUserRoute,
  ApiOrganizationsRemoveUserRoute: ApiOrganizationsRemoveUserRoute,
}

const ApiOrganizationsRouteWithChildren =
  ApiOrganizationsRoute._addFileChildren(ApiOrganizationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  FixedIncomeRoute: FixedIncomeRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvestmentsRoute: InvestmentsRoute,
  MealsOutRoute: MealsOutRoute,
  PaymentsRoute: PaymentsRoute,
  ReceiptsRoute: ReceiptsRoute,
  RegisterRoute: RegisterRoute,
  RetirementRoute: RetirementRoute,
  SetPasswordRoute: SetPasswordRoute,
  TasksRoute: TasksRoute,
  TaxesRoute: TaxesRoute,
  TrendsRoute: TrendsRoute,
  ApiForgotPasswordRoute: ApiForgotPasswordRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiOrganizationsRoute: ApiOrganizationsRouteWithChildren,
  ApiRegisterRoute: ApiRegisterRoute,
  ApiResetPasswordRoute: ApiResetPasswordRoute,
  ApiTickerPricesRoute: ApiTickerPricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
